"""MaxObject stubs for m4l objects. Auto-generated by import_m4l()."""
import os as _os
import sys as _sys
from maxpylang.maxobject import MaxObject

__all__ = [
    'chucker_tilde',
    'cverb_tilde',
    'ddg_mono',
    'live_arrows',
    'live_banks',
    'live_button',
    'live_colors',
    'live_comment',
    'live_dial',
    'live_drop',
    'live_gain_tilde',
    'live_grid',
    'live_line',
    'live_map',
    'live_menu',
    'live_meter_tilde',
    'live_miditool_in',
    'live_miditool_out',
    'live_modulate_tilde',
    'live_numbox',
    'live_object',
    'live_observer',
    'live_param_tilde',
    'live_path',
    'live_push',
    'live_remote_tilde',
    'live_routing',
    'live_slider',
    'live_step',
    'live_tab',
    'live_text',
    'live_thisdevice',
    'live_toggle',
    'mc_live_gain_tilde',
    'midiselect',
]

_devnull = open(_os.devnull, 'w')
_old_stdout = _sys.stdout
_sys.stdout = _devnull

"""chucker~ - Segment audio and reorder it on looped playback"""
chucker_tilde = MaxObject('chucker~')

"""cverb~ - A simple monaural reverberator"""
cverb_tilde = MaxObject('cverb~')

"""ddg.mono - Monophonic Synth Controller for Virtual Synths"""
ddg_mono = MaxObject('ddg.mono')

"""live.arrows - Vectorized arrow(s) user interface object"""
live_arrows = MaxObject('live.arrows')

"""live.banks - Manage Max for Live Device banks for Push controllers."""
live_banks = MaxObject('live.banks')

"""live.button - Flash on any message, send a bang"""
live_button = MaxObject('live.button')

"""live.colors - Get the colors of the active Ableton Live Theme via a Max for Live device."""
live_colors = MaxObject('live.colors')

"""live.comment - Explanatory note or label (Max for Live)"""
live_comment = MaxObject('live.comment')

"""live.dial - Output numbers by moving a dial onscreen"""
live_dial = MaxObject('live.dial')

"""live.drop - Define a region for dragging and dropping a file"""
live_drop = MaxObject('live.drop')

"""live.gain~ - Decibel volume slider and monitor"""
live_gain_tilde = MaxObject('live.gain~')

"""live.grid - A UI grid of steps, with constraints and directions"""
live_grid = MaxObject('live.grid')

"""live.line - Straight line"""
live_line = MaxObject('live.line')

"""live.map - Simplify the process of selecting Live interface elements for use with the Live API."""
live_map = MaxObject('live.map')

"""live.menu - Dropdown menu"""
live_menu = MaxObject('live.menu')

"""live.meter~ - Live-style visual peak level indicator"""
live_meter_tilde = MaxObject('live.meter~')

"""live.miditool.in - Retrieve notes and contextual data of MIDI clips in Live. Designed for use in a MIDI Tool Generator or MIDI Tool Transformation."""
live_miditool_in = MaxObject('live.miditool.in')

"""live.miditool.out - Set or replace notes of MIDI clips in Live. Designed for use in a MIDI Tool Generator or MIDI Tool Transformation."""
live_miditool_out = MaxObject('live.miditool.out')

"""live.modulate~ - Modulate Ableton Live and Max for Live Parameters"""
live_modulate_tilde = MaxObject('live.modulate~')

"""live.numbox - Display and output a number"""
live_numbox = MaxObject('live.numbox')

"""live.object - Perform operations on Live objects"""
live_object = MaxObject('live.object')

"""live.observer - Monitor changes in Live objects"""
live_observer = MaxObject('live.observer')

"""live.param~ - Generate an MSP signal from a parameter value."""
live_param_tilde = MaxObject('live.param~')

"""live.path - Navigate to objects in the Live application"""
live_path = MaxObject('live.path')

"""live.push - Configuration of Push 2 and 3"""
live_push = MaxObject('live.push')

"""live.remote~ - Realtime control of parameters in Ableton Live and Max for Live."""
live_remote_tilde = MaxObject('live.remote~')

"""live.routing - Route MIDI and Audio Inputs and Outputs in Ableton Live"""
live_routing = MaxObject('live.routing')

"""live.slider - Output numbers by moving a slider onscreen"""
live_slider = MaxObject('live.slider')

"""live.step - Step Sequencer UI object"""
live_step = MaxObject('live.step')

"""live.tab - A user interface tab/multiple button object in the style of Ableton Live."""
live_tab = MaxObject('live.tab')

"""live.text - A user interface button/toggle"""
live_text = MaxObject('live.text')

"""live.thisdevice - Send a bang automatically when a Max Device is loaded, report device state"""
live_thisdevice = MaxObject('live.thisdevice')

"""live.toggle - Switch between off and on (0/1)"""
live_toggle = MaxObject('live.toggle')

"""mc.live.gain~ - Decibel volume slider and monitor"""
mc_live_gain_tilde = MaxObject('mc.live.gain~')

"""midiselect - Select and interpret raw MIDI data"""
midiselect = MaxObject('midiselect')

_sys.stdout = _old_stdout
_devnull.close()
del _devnull, _old_stdout
